### ISSUE TITLE
Chaturbate: Models who are online not seen as such (and therefore not captured)

### ISSUE THREAD

**Issue by MrSpuck** [jrudess/mfc_cb.node#29]
Some models (i.e. miiiawallace, sophiesticated, blowjobjosie) when online are not seen as such by your software and are not being captured. 

Possibly related to #26.

**Comment by fanout96** [comment]
In my repository there is a fork in which this problem is fixed, but my version still needs improvement, because it seems to me that I have a memory leak

**Comment by jrudess** [comment]
Yeah, the CB code has some issues.  Looks like fanout96 found a bug with a missing 'group show' check in his branch.   

But I do know that the json file that I am fetching from CB can have up to 30 minute lag for updates:
* New models won't show as online -- no workaround
* Disconnected models won't show as being offline -- I worked around this by disabling an error-message for now).

fanout96's branch looks like it has good fixes, and hopefully I can get those back into this branch to help solve the issues.

**Comment by jrudess** [comment]
The patches are now merged into master branch.  Running with this fix for a few days on my side, and will close out once an official release tag is applied.

**Comment by jrudess** [comment]
Please reopen this issue if v0.5.0 does not solve the issues for you.
